SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE `add_ons` (
  `id` varchar(36) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `long_description` text DEFAULT NULL,
  `category` enum('integration','feature','support','capacity') NOT NULL,
  `pricing_type` enum('one_time','recurring') NOT NULL DEFAULT 'recurring',
  `price` decimal(10,2) NOT NULL,
  `status` enum('active','inactive','coming_soon') NOT NULL DEFAULT 'active',
  `icon_url` varchar(255) DEFAULT NULL,
  `features` text DEFAULT NULL,
  `available_for_plans` text NOT NULL DEFAULT '[]',
  `metadata` text DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_61c3fff7bb3379d678445d7c02` (`slug`),
  KEY `IDX_7b54670015d05db80060280ee0` (`status`),
  KEY `IDX_cf4165c5f6dfab368ff296d73f` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `admin_users` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `name` varchar(150) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` enum('super_admin','admin') NOT NULL DEFAULT 'admin',
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `last_login_at` timestamp NULL DEFAULT NULL,
  `last_login_ip` varchar(45) DEFAULT NULL,
  `two_factor_enabled` tinyint(4) NOT NULL DEFAULT 0,
  `two_factor_secret` varchar(255) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_dcd0c8a4b10af9c986e510b9ec` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `audit_logs` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `companyId` varchar(255) DEFAULT NULL,
  `action` varchar(100) NOT NULL,
  `entityType` varchar(100) NOT NULL,
  `entityId` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `oldValues` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`oldValues`)),
  `newValues` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`newValues`)),
  `userId` varchar(255) DEFAULT NULL,
  `userType` varchar(50) DEFAULT NULL,
  `ipAddress` varchar(100) DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  PRIMARY KEY (`id`),
  KEY `IDX_efa597fecfef3d3ec683d69332` (`companyId`),
  KEY `IDX_cee5459245f652b75eb2759b4c` (`action`),
  KEY `IDX_01993ae76b293d3b866cc3a125` (`entityType`),
  KEY `IDX_cfa83f61e4d27a87fcae1e025a` (`userId`),
  KEY `IDX_2254c368e04a5fbfe583f73638` (`userId`,`created_at`),
  KEY `IDX_3045bfdb8a84c4540497424fef` (`companyId`,`entityType`,`entityId`),
  KEY `IDX_c79edfab6c7719d0f520f3ca1a` (`companyId`,`action`),
  KEY `IDX_d40f5a2de312baf7d3ab7073f6` (`companyId`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `categories` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `name` varchar(100) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `image_url` varchar(500) DEFAULT NULL,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `company_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `parent_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_5848ba82e61b83e2aa416447a15` (`store_id`),
  KEY `FK_88cea2dc9c31951d06437879b40` (`parent_id`),
  CONSTRAINT `FK_5848ba82e61b83e2aa416447a15` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_88cea2dc9c31951d06437879b40` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `companies` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `name` varchar(200) NOT NULL,
  `slug` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `business_type` varchar(50) DEFAULT NULL,
  `business_registration_number` varchar(100) DEFAULT NULL,
  `tax_id` varchar(100) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `postal_code` varchar(10) DEFAULT NULL,
  `country` varchar(2) NOT NULL DEFAULT 'ID',
  `logo_url` varchar(500) DEFAULT NULL,
  `primary_color` varchar(7) NOT NULL DEFAULT '#10b981',
  `timezone` varchar(50) NOT NULL DEFAULT 'Asia/Jakarta',
  `currency` varchar(3) NOT NULL DEFAULT 'IDR',
  `language` varchar(5) NOT NULL DEFAULT 'id',
  `status` varchar(50) NOT NULL DEFAULT 'active',
  `is_email_verified` tinyint(4) NOT NULL DEFAULT 0,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `current_plan_id` varchar(255) DEFAULT NULL,
  `subscription_status` varchar(50) DEFAULT NULL,
  `trial_ends_at` timestamp NULL DEFAULT NULL,
  `subscription_ends_at` timestamp NULL DEFAULT NULL,
  `payment_gateway_preference` varchar(20) DEFAULT 'xendit',
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}' CHECK (json_valid(`metadata`)),
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_b28b07d25e4324eee577de5496` (`slug`),
  UNIQUE KEY `IDX_d0af6f5866201d5cb424767744` (`email`),
  KEY `FK_8f49290c1d2c51ee54eae1e85ad` (`current_plan_id`),
  CONSTRAINT `FK_8f49290c1d2c51ee54eae1e85ad` FOREIGN KEY (`current_plan_id`) REFERENCES `subscription_plans` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `company_add_ons` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `add_on_id` varchar(255) NOT NULL,
  `status` enum('active','pending_payment','expired','cancelled') NOT NULL DEFAULT 'pending_payment',
  `purchase_price` decimal(10,2) NOT NULL,
  `invoice_id` varchar(255) DEFAULT NULL,
  `payment_transaction_id` varchar(255) DEFAULT NULL,
  `activated_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `cancelled_at` timestamp NULL DEFAULT NULL,
  `auto_renew` tinyint(4) NOT NULL DEFAULT 1,
  `configuration` text DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `IDX_ff69a0f6c10945400e125cf90f` (`expires_at`),
  KEY `IDX_67e895c25c124480fe0e1580d7` (`status`),
  KEY `IDX_eb6e137633e2735246b0db1c43` (`company_id`,`add_on_id`),
  KEY `FK_87ea3dfc2ab391edecd07059c28` (`add_on_id`),
  CONSTRAINT `FK_16497c4e6e1644210e383e9002b` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_87ea3dfc2ab391edecd07059c28` FOREIGN KEY (`add_on_id`) REFERENCES `add_ons` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `customers` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `customer_number` varchar(50) NOT NULL,
  `name` varchar(150) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `postal_code` varchar(10) DEFAULT NULL,
  `loyalty_points` int(11) NOT NULL DEFAULT 0,
  `loyalty_tier` enum('regular','silver','gold','platinum') NOT NULL DEFAULT 'regular',
  `total_spent` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_orders` int(11) NOT NULL DEFAULT 0,
  `date_of_birth` date DEFAULT NULL,
  `gender` enum('male','female','other') DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `first_purchase_at` timestamp NULL DEFAULT NULL,
  `last_purchase_at` timestamp NULL DEFAULT NULL,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}' CHECK (json_valid(`metadata`)),
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_6fbe8c55d8dd968877d296493e` (`customer_number`),
  KEY `FK_f0e29920aaf871f3eddbea69f0d` (`company_id`),
  KEY `FK_2501b8750977dd4f4d06dfeff07` (`store_id`),
  CONSTRAINT `FK_2501b8750977dd4f4d06dfeff07` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_f0e29920aaf871f3eddbea69f0d` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `discount_usages` (
  `id` varchar(36) NOT NULL,
  `discount_id` varchar(255) NOT NULL,
  `customer_id` varchar(255) DEFAULT NULL,
  `transaction_id` varchar(255) NOT NULL,
  `discount_amount` decimal(12,2) NOT NULL,
  `used_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `FK_e522ffed68f1b6f1b5c64279d03` (`discount_id`),
  KEY `FK_686361dee5f7fec2738d77c919b` (`customer_id`),
  KEY `FK_2b8d40b5fca2fe3f39dc3a700a0` (`transaction_id`),
  CONSTRAINT `FK_2b8d40b5fca2fe3f39dc3a700a0` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_686361dee5f7fec2738d77c919b` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_e522ffed68f1b6f1b5c64279d03` FOREIGN KEY (`discount_id`) REFERENCES `discounts` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `discounts` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `type` enum('percentage','fixed','buy_x_get_y','voucher') NOT NULL,
  `value` decimal(12,2) NOT NULL,
  `minTransaction` decimal(12,2) DEFAULT NULL,
  `maxDiscount` decimal(12,2) DEFAULT NULL,
  `promoCode` varchar(50) DEFAULT NULL,
  `scope` enum('all','category','product') NOT NULL DEFAULT 'all',
  `applicableIds` text DEFAULT NULL,
  `usageLimit` int(11) DEFAULT NULL,
  `usageCount` int(11) NOT NULL DEFAULT 0,
  `usageLimitPerCustomer` int(11) DEFAULT NULL,
  `startDate` datetime DEFAULT NULL,
  `endDate` datetime DEFAULT NULL,
  `isActive` tinyint(4) NOT NULL DEFAULT 1,
  `company_id` varchar(255) NOT NULL,
  `store_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_21fc8b5cb454c415de5ad14b60` (`promoCode`),
  KEY `FK_2bb55b1d0e4dd71a00b1ce80e3d` (`company_id`),
  KEY `FK_588bdd45fd5a79cad73113e871d` (`store_id`),
  CONSTRAINT `FK_2bb55b1d0e4dd71a00b1ce80e3d` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_588bdd45fd5a79cad73113e871d` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `email_configs` (
  `id` varchar(36) NOT NULL,
  `provider` enum('mailtrap','gmail','smtp') NOT NULL DEFAULT 'mailtrap',
  `is_enabled` tinyint(4) NOT NULL DEFAULT 0,
  `host` varchar(200) DEFAULT NULL,
  `port` int(11) DEFAULT NULL,
  `secure` tinyint(4) NOT NULL DEFAULT 0,
  `username` varchar(200) DEFAULT NULL,
  `password` text DEFAULT NULL,
  `from_name` varchar(200) DEFAULT NULL,
  `from_email` varchar(200) DEFAULT NULL,
  `oauth_client_id` text DEFAULT NULL,
  `oauth_client_secret` text DEFAULT NULL,
  `oauth_refresh_token` text DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `email_verification_tokens` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `user_id` varchar(255) NOT NULL,
  `email` varchar(100) NOT NULL,
  `token` varchar(255) NOT NULL,
  `expires_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `used_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_3d1613f95c6a564a3b588d161a` (`token`),
  KEY `FK_fdcb77f72f529bf65c95d72a147` (`user_id`),
  CONSTRAINT `FK_fdcb77f72f529bf65c95d72a147` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `employees` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `user_id` varchar(255) DEFAULT NULL,
  `store_id` varchar(255) DEFAULT NULL,
  `name` varchar(150) NOT NULL,
  `email` varchar(100) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `pin` varchar(6) DEFAULT NULL,
  `employee_number` varchar(50) NOT NULL,
  `position` varchar(100) DEFAULT NULL,
  `hire_date` date NOT NULL,
  `salary` decimal(15,2) NOT NULL DEFAULT 0.00,
  `avatar_url` varchar(500) DEFAULT NULL,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_8878710dc844ecd6f9e587f34f` (`employee_number`),
  KEY `FK_7f3eeef59eece4147effe7bfa6a` (`company_id`),
  KEY `FK_2d83c53c3e553a48dadb9722e38` (`user_id`),
  KEY `FK_c7da9c52c80593b9b657051923a` (`store_id`),
  CONSTRAINT `FK_2d83c53c3e553a48dadb9722e38` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_7f3eeef59eece4147effe7bfa6a` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_c7da9c52c80593b9b657051923a` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `features` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `name` varchar(100) NOT NULL,
  `code` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `isActive` tinyint(4) NOT NULL DEFAULT 1,
  `company_id` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_c0e1f5d0ba8027c186705d752b` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `fnb_modifier_groups` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `type` enum('single','multiple') NOT NULL DEFAULT 'single',
  `required` tinyint(4) NOT NULL DEFAULT 0,
  `min_selections` int(11) NOT NULL DEFAULT 1,
  `max_selections` int(11) DEFAULT NULL,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `product_ids` text DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `FK_6a9cb325c3092760e3b2ace9179` (`company_id`),
  CONSTRAINT `FK_6a9cb325c3092760e3b2ace9179` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `fnb_modifier_options` (
  `id` varchar(36) NOT NULL,
  `group_id` varchar(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `additional_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `is_available` tinyint(4) NOT NULL DEFAULT 1,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `FK_689edd186fd58b45df0a9b1b54f` (`group_id`),
  CONSTRAINT `FK_689edd186fd58b45df0a9b1b54f` FOREIGN KEY (`group_id`) REFERENCES `fnb_modifier_groups` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `fnb_orders` (
  `id` varchar(36) NOT NULL,
  `order_number` varchar(50) NOT NULL,
  `order_type` enum('dine-in','takeaway','delivery') NOT NULL,
  `status` enum('pending','preparing','ready','served','completed','cancelled') NOT NULL DEFAULT 'pending',
  `company_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `table_id` varchar(255) DEFAULT NULL,
  `transaction_id` varchar(255) DEFAULT NULL,
  `delivery_address` text DEFAULT NULL,
  `delivery_fee` decimal(10,2) NOT NULL DEFAULT 0.00,
  `notes` text DEFAULT NULL,
  `preparing_at` timestamp NULL DEFAULT NULL,
  `ready_at` timestamp NULL DEFAULT NULL,
  `served_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_763d079502ae7982aa4fbfc8ad` (`order_number`),
  UNIQUE KEY `REL_3b21f99d3114be3f542a18395c` (`transaction_id`),
  KEY `FK_51d384b1e271df2b7a51dd5e6eb` (`company_id`),
  KEY `FK_ab06c9fb725fa20c5e95b468eb8` (`store_id`),
  KEY `FK_bc5e0e0f3346cc65c028909f2d6` (`table_id`),
  CONSTRAINT `FK_3b21f99d3114be3f542a18395c4` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_51d384b1e271df2b7a51dd5e6eb` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ab06c9fb725fa20c5e95b468eb8` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_bc5e0e0f3346cc65c028909f2d6` FOREIGN KEY (`table_id`) REFERENCES `tables` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `invoices` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `subscription_id` varchar(255) DEFAULT NULL,
  `invoice_number` varchar(50) NOT NULL,
  `invoice_type` enum('subscription','add_on','renewal') NOT NULL DEFAULT 'subscription',
  `invoice_pdf_url` varchar(500) DEFAULT NULL,
  `add_on_id` varchar(255) DEFAULT NULL,
  `company_add_on_id` varchar(255) DEFAULT NULL,
  `subtotal` decimal(12,2) NOT NULL,
  `tax_rate` decimal(5,2) NOT NULL DEFAULT 0.00,
  `tax_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `discount_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total` decimal(12,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'IDR',
  `status` enum('draft','pending','paid','failed','refunded','cancelled') NOT NULL,
  `issue_date` date NOT NULL,
  `due_date` date NOT NULL,
  `paid_at` timestamp NULL DEFAULT NULL,
  `payment_method` varchar(50) DEFAULT NULL,
  `payment_reference` varchar(100) DEFAULT NULL,
  `payment_url` text DEFAULT NULL,
  `line_items` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '[]' CHECK (json_valid(`line_items`)),
  `notes` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_d8f8d3788694e1b3f96c42c36f` (`invoice_number`),
  KEY `FK_42385e42f092f26bd38df549717` (`company_id`),
  KEY `FK_5152c0aa0f851d9b95972b442e0` (`subscription_id`),
  CONSTRAINT `FK_42385e42f092f26bd38df549717` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_5152c0aa0f851d9b95972b442e0` FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `landing_contents` (
  `id` varchar(36) NOT NULL,
  `section` varchar(100) NOT NULL,
  `title` varchar(200) NOT NULL,
  `content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`content`)),
  `isVisible` tinyint(4) NOT NULL DEFAULT 1,
  `sortOrder` int(11) NOT NULL DEFAULT 0,
  `createdAt` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_4af0431afb82f17c82205162d1` (`section`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `laundry_items` (
  `id` varchar(36) NOT NULL,
  `order_id` varchar(255) NOT NULL,
  `item_type` enum('shirt','pants','dress','jacket','skirt','bedsheet','blanket','curtain','towel','other') NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  `color` varchar(100) DEFAULT NULL,
  `brand` varchar(100) DEFAULT NULL,
  `quantity` int(11) NOT NULL DEFAULT 1,
  `barcode` varchar(50) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_bb018df6160634d4dcdc0c98ae` (`barcode`),
  KEY `FK_e50e56c83b18fb01b16aa418828` (`order_id`),
  CONSTRAINT `FK_e50e56c83b18fb01b16aa418828` FOREIGN KEY (`order_id`) REFERENCES `laundry_orders` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `laundry_orders` (
  `id` varchar(36) NOT NULL,
  `order_number` varchar(50) NOT NULL,
  `status` enum('received','washing','drying','ironing','ready','delivered','cancelled') NOT NULL DEFAULT 'received',
  `company_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `customer_id` varchar(255) NOT NULL,
  `service_type_id` varchar(255) NOT NULL,
  `weight_kg` decimal(10,2) DEFAULT NULL,
  `item_count` int(11) NOT NULL DEFAULT 0,
  `total_price` decimal(10,2) NOT NULL,
  `notes` text DEFAULT NULL,
  `pickup_date` timestamp NULL DEFAULT NULL,
  `delivery_date` timestamp NULL DEFAULT NULL,
  `pickup_address` varchar(500) DEFAULT NULL,
  `delivery_address` varchar(500) DEFAULT NULL,
  `washing_started_at` timestamp NULL DEFAULT NULL,
  `drying_started_at` timestamp NULL DEFAULT NULL,
  `ironing_started_at` timestamp NULL DEFAULT NULL,
  `ready_at` timestamp NULL DEFAULT NULL,
  `delivered_at` timestamp NULL DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_932d01ca621fd28257f294e0f5` (`order_number`),
  KEY `FK_50fdbc613fc65ec0186f51e3d4b` (`company_id`),
  KEY `FK_11ed094328f639ca2b6049a39ad` (`store_id`),
  KEY `FK_bfac172cb5fb243fc90e10b4574` (`customer_id`),
  KEY `FK_e6a9f6c8f1e13b823493204726b` (`service_type_id`),
  CONSTRAINT `FK_11ed094328f639ca2b6049a39ad` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_50fdbc613fc65ec0186f51e3d4b` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_bfac172cb5fb243fc90e10b4574` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_e6a9f6c8f1e13b823493204726b` FOREIGN KEY (`service_type_id`) REFERENCES `laundry_service_types` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `laundry_service_types` (
  `id` varchar(36) NOT NULL,
  `name` varchar(100) NOT NULL,
  `service_type` enum('wash_dry','wash_iron','dry_clean','iron_only') NOT NULL,
  `description` text DEFAULT NULL,
  `pricing_type` enum('per_kg','per_item') NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `estimated_hours` int(11) NOT NULL DEFAULT 24 COMMENT 'Estimated completion time in hours',
  `company_id` varchar(255) NOT NULL,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `FK_5015008e5609d87102270c1e583` (`company_id`),
  CONSTRAINT `FK_5015008e5609d87102270c1e583` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `notifications` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) DEFAULT NULL,
  `user_id` varchar(255) DEFAULT NULL,
  `subscription_id` varchar(255) DEFAULT NULL,
  `type` enum('invoice','payment','subscription','subscription_expiring','subscription_expired','subscription_suspended','system','alert') NOT NULL,
  `title` varchar(200) NOT NULL,
  `message` text NOT NULL,
  `data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}' CHECK (json_valid(`data`)),
  `channel` enum('email','in_app','sms','whatsapp') DEFAULT NULL,
  `scheduled_for` date DEFAULT NULL,
  `sent_at` timestamp NULL DEFAULT NULL,
  `is_read` tinyint(4) NOT NULL DEFAULT 0,
  `read_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_c642fb845de2edcae46635863ab` (`company_id`),
  KEY `FK_9a8a82462cab47c73d25f49261f` (`user_id`),
  CONSTRAINT `FK_9a8a82462cab47c73d25f49261f` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_c642fb845de2edcae46635863ab` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `password_reset_tokens` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `user_id` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `expires_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `used_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_ab673f0e63eac966762155508e` (`token`),
  KEY `FK_52ac39dd8a28730c63aeb428c9c` (`user_id`),
  CONSTRAINT `FK_52ac39dd8a28730c63aeb428c9c` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `payment_gateway_configs` (
  `id` varchar(36) NOT NULL,
  `gateway` varchar(50) NOT NULL,
  `isEnabled` tinyint(4) NOT NULL DEFAULT 0,
  `secretKey` text DEFAULT NULL,
  `webhookToken` text DEFAULT NULL,
  `webhookUrl` text DEFAULT NULL,
  `isProduction` tinyint(4) NOT NULL DEFAULT 0,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metadata`)),
  `createdAt` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_a1e27ebf83e01cf6ee7a14674a` (`gateway`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `payment_methods` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `code` varchar(50) NOT NULL,
  `type` enum('cash','card','ewallet','bank_transfer','qris','other') NOT NULL DEFAULT 'cash',
  `icon_url` varchar(255) DEFAULT NULL,
  `color` varchar(20) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `requires_reference` tinyint(4) NOT NULL DEFAULT 0,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `account_code` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_payment_methods_company_code` (`company_id`,`code`),
  KEY `IDX_payment_methods_type` (`type`),
  KEY `IDX_payment_methods_active` (`is_active`),
  KEY `IDX_payment_methods_company` (`company_id`),
  CONSTRAINT `FK_c5fe30363cf2f9a0f51c5cd987e` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `payment_transactions` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `invoice_id` varchar(255) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `gateway` enum('midtrans','xendit','stripe') NOT NULL,
  `gateway_transaction_id` varchar(100) DEFAULT NULL,
  `amount` decimal(12,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'IDR',
  `status` enum('pending','success','failed','expired','refunded') NOT NULL,
  `payment_method` varchar(50) DEFAULT NULL,
  `payment_channel` varchar(50) DEFAULT NULL,
  `gateway_request` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`gateway_request`)),
  `gateway_response` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`gateway_response`)),
  `completed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_07b209d806ee9b5d22e0209c2a` (`gateway_transaction_id`),
  KEY `FK_d43f7ac66aab4c15fc030c46fa3` (`invoice_id`),
  KEY `FK_c37870f6c86ba2d2e4f7bee21c2` (`company_id`),
  CONSTRAINT `FK_c37870f6c86ba2d2e4f7bee21c2` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_d43f7ac66aab4c15fc030c46fa3` FOREIGN KEY (`invoice_id`) REFERENCES `invoices` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `permissions` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `code` varchar(100) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_8dad765629e83229da6feda1c1` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `product_variants` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `name` varchar(100) NOT NULL,
  `priceAdjustment` decimal(12,2) NOT NULL,
  `sku` varchar(50) DEFAULT NULL,
  `stock` int(11) NOT NULL DEFAULT 0,
  `isActive` tinyint(4) NOT NULL DEFAULT 1,
  `product_id` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_6343513e20e2deab45edfce1316` (`product_id`),
  CONSTRAINT `FK_6343513e20e2deab45edfce1316` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `products` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `category_id` varchar(255) DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `sku` varchar(100) DEFAULT NULL,
  `barcode` varchar(100) DEFAULT NULL,
  `cost` decimal(12,2) NOT NULL DEFAULT 0.00,
  `price` decimal(12,2) NOT NULL,
  `compare_at_price` decimal(12,2) DEFAULT NULL,
  `track_inventory` tinyint(4) NOT NULL DEFAULT 1,
  `stock` int(11) NOT NULL DEFAULT 0,
  `low_stock_threshold` int(11) NOT NULL DEFAULT 10,
  `type` enum('physical','digital','service') NOT NULL DEFAULT 'physical',
  `image_url` varchar(500) DEFAULT NULL,
  `images` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '[]' CHECK (json_valid(`images`)),
  `has_variants` tinyint(4) NOT NULL DEFAULT 0,
  `is_taxable` tinyint(4) NOT NULL DEFAULT 1,
  `tax_rate` decimal(5,2) DEFAULT NULL,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}' CHECK (json_valid(`metadata`)),
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_b417f1726f6ccafb18730adffb0` (`company_id`),
  KEY `FK_68863607048a1abd43772b314ef` (`store_id`),
  KEY `FK_9a5f6868c96e0069e699f33e124` (`category_id`),
  CONSTRAINT `FK_68863607048a1abd43772b314ef` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_9a5f6868c96e0069e699f33e124` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_b417f1726f6ccafb18730adffb0` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `purchase_order_items` (
  `id` varchar(36) NOT NULL,
  `purchase_order_id` varchar(255) NOT NULL,
  `product_id` varchar(255) NOT NULL,
  `product_name` varchar(200) NOT NULL,
  `product_sku` varchar(100) DEFAULT NULL,
  `quantity_ordered` int(11) NOT NULL,
  `quantity_received` int(11) NOT NULL DEFAULT 0,
  `unit` varchar(50) DEFAULT NULL,
  `unit_price` decimal(15,2) NOT NULL,
  `total_price` decimal(15,2) NOT NULL,
  `notes` text DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `IDX_d5089517fc19b1b9fb04454740` (`product_id`),
  KEY `IDX_3f92bb44026cedfe235c8b9124` (`purchase_order_id`),
  CONSTRAINT `FK_3f92bb44026cedfe235c8b91244` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `purchase_orders` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `po_number` varchar(50) NOT NULL,
  `supplier_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `status` enum('draft','sent','received','cancelled') NOT NULL DEFAULT 'draft',
  `order_date` date NOT NULL,
  `expected_delivery_date` date DEFAULT NULL,
  `received_date` date DEFAULT NULL,
  `received_by` varchar(255) DEFAULT NULL,
  `subtotal` decimal(15,2) NOT NULL DEFAULT 0.00,
  `tax_rate` decimal(5,2) NOT NULL DEFAULT 0.00,
  `tax_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `discount_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `shipping_cost` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total` decimal(15,2) NOT NULL DEFAULT 0.00,
  `notes` text DEFAULT NULL,
  `terms_and_conditions` text DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_74065a5d2b8c4c14b8b8fcf015` (`po_number`),
  KEY `IDX_5272ac3aa931eedb14cd8789d6` (`status`),
  KEY `IDX_d650fc880f79ca82d962773a7c` (`store_id`),
  KEY `IDX_d16a885aa88447ccfd010e739b` (`supplier_id`),
  KEY `IDX_caed0f51e45442af8cea5c410b` (`company_id`),
  KEY `FK_99f44faa1ca8d7ec9ebef918b06` (`created_by`),
  KEY `FK_9a28c78df239aa6164db25fa6be` (`received_by`),
  CONSTRAINT `FK_99f44faa1ca8d7ec9ebef918b06` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_9a28c78df239aa6164db25fa6be` FOREIGN KEY (`received_by`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_caed0f51e45442af8cea5c410b2` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_d16a885aa88447ccfd010e739b0` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_d650fc880f79ca82d962773a7c1` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `qris_configs` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `originalImage` text NOT NULL,
  `parsedData` text DEFAULT NULL,
  `merchantName` varchar(100) DEFAULT NULL,
  `merchantId` varchar(100) DEFAULT NULL,
  `isActive` tinyint(4) NOT NULL DEFAULT 1,
  `store_id` varchar(255) DEFAULT NULL,
  `company_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_2e429e8564aec62b024d445303b` (`store_id`),
  KEY `FK_dd800a2ae901e26e572b4ee84d5` (`company_id`),
  CONSTRAINT `FK_2e429e8564aec62b024d445303b` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_dd800a2ae901e26e572b4ee84d5` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `role_permissions` (
  `role_id` varchar(36) NOT NULL,
  `permission_id` varchar(36) NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `IDX_178199805b901ccd220ab7740e` (`role_id`),
  KEY `IDX_17022daf3f885f7d35423e9971` (`permission_id`),
  CONSTRAINT `FK_17022daf3f885f7d35423e9971e` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_178199805b901ccd220ab7740ec` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `roles` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `name` varchar(50) NOT NULL,
  `description` text DEFAULT NULL,
  `isSystemRole` tinyint(4) NOT NULL DEFAULT 0,
  `store_id` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_c9f877a44914320ba21b00b7465` (`store_id`),
  CONSTRAINT `FK_c9f877a44914320ba21b00b7465` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `shifts` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `employee_id` varchar(255) DEFAULT NULL,
  `user_id` varchar(255) DEFAULT NULL,
  `opened_at` timestamp NULL DEFAULT NULL,
  `closed_at` timestamp NULL DEFAULT NULL,
  `opening_cash` decimal(12,2) NOT NULL,
  `closing_cash` decimal(12,2) DEFAULT NULL,
  `opening_cash_breakdown` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`opening_cash_breakdown`)),
  `closing_cash_breakdown` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`closing_cash_breakdown`)),
  `expected_cash` decimal(12,2) DEFAULT NULL,
  `cash_difference` decimal(12,2) DEFAULT NULL,
  `total_sales` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total_transactions` int(11) NOT NULL DEFAULT 0,
  `cash_sales` decimal(12,2) NOT NULL DEFAULT 0.00,
  `card_sales` decimal(12,2) NOT NULL DEFAULT 0.00,
  `qris_sales` decimal(12,2) NOT NULL DEFAULT 0.00,
  `ewallet_sales` decimal(12,2) NOT NULL DEFAULT 0.00,
  `bank_transfer_sales` decimal(12,2) NOT NULL DEFAULT 0.00,
  `status` enum('open','closed') NOT NULL DEFAULT 'open',
  `opening_notes` text DEFAULT NULL,
  `closing_notes` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_e155f8dd2a50f91604c8d946369` (`company_id`),
  KEY `FK_39e04f82d2ccc83f89df4767a8d` (`store_id`),
  KEY `FK_47935d717a7c66cb9e8ac08df82` (`employee_id`),
  CONSTRAINT `FK_39e04f82d2ccc83f89df4767a8d` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_47935d717a7c66cb9e8ac08df82` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_e155f8dd2a50f91604c8d946369` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `stock_movements` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `product_id` varchar(255) NOT NULL,
  `variant_id` varchar(255) DEFAULT NULL,
  `type` enum('in','out','adjustment','return','sale','transfer') NOT NULL,
  `quantity` int(11) NOT NULL,
  `stock_after` int(11) NOT NULL DEFAULT 0 COMMENT 'Stock level after this movement',
  `reason` varchar(255) DEFAULT NULL,
  `reference` varchar(100) DEFAULT NULL COMMENT 'e.g. invoice number or transaction ID',
  `performed_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_5c64f92a726ebd11df7f4a45ae6` (`company_id`),
  KEY `FK_5914e3685851db1a0be9733594f` (`store_id`),
  KEY `FK_2c1bb05b80ddcc562cd28d826c6` (`product_id`),
  KEY `FK_fffd5f1c504a8eb2917e93313ba` (`variant_id`),
  KEY `FK_8a1479840f8ba413f8d5c95c52e` (`performed_by`),
  CONSTRAINT `FK_2c1bb05b80ddcc562cd28d826c6` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_5914e3685851db1a0be9733594f` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_5c64f92a726ebd11df7f4a45ae6` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_8a1479840f8ba413f8d5c95c52e` FOREIGN KEY (`performed_by`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_fffd5f1c504a8eb2917e93313ba` FOREIGN KEY (`variant_id`) REFERENCES `product_variants` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `stock_opname_items` (
  `id` varchar(36) NOT NULL,
  `stock_opname_id` varchar(255) NOT NULL,
  `product_id` varchar(255) NOT NULL,
  `product_name` varchar(200) NOT NULL,
  `product_sku` varchar(100) DEFAULT NULL,
  `system_quantity` int(11) NOT NULL,
  `physical_quantity` int(11) NOT NULL,
  `difference` int(11) NOT NULL,
  `unit` varchar(50) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `is_adjusted` tinyint(4) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  KEY `IDX_adba2f4a1a00330641c196f319` (`product_id`),
  KEY `IDX_b0b3f97611ef87a906efba79e4` (`stock_opname_id`),
  CONSTRAINT `FK_b0b3f97611ef87a906efba79e41` FOREIGN KEY (`stock_opname_id`) REFERENCES `stock_opnames` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `stock_opnames` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `opname_number` varchar(50) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `status` enum('in_progress','completed','cancelled') NOT NULL DEFAULT 'in_progress',
  `opname_date` date NOT NULL,
  `completed_at` datetime DEFAULT NULL,
  `completed_by` varchar(255) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `total_items` int(11) NOT NULL DEFAULT 0,
  `total_discrepancies` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_99c002da8e6c5da38998b42671` (`opname_number`),
  KEY `IDX_bf073276a22b7a4891dc5adba1` (`status`),
  KEY `IDX_2d3a2f18ee2ce6e4c257dc58ce` (`store_id`),
  KEY `IDX_a50189547e84ed433132bff246` (`company_id`),
  KEY `FK_2d1eedcc5f8b58ebc0c588390a8` (`created_by`),
  KEY `FK_b40eacdf3c3b1e82918705484bd` (`completed_by`),
  CONSTRAINT `FK_2d1eedcc5f8b58ebc0c588390a8` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_2d3a2f18ee2ce6e4c257dc58cef` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_a50189547e84ed433132bff2465` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_b40eacdf3c3b1e82918705484bd` FOREIGN KEY (`completed_by`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `store_payment_methods` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `type` enum('cash','qris','bank_transfer','edc','ewallet') NOT NULL,
  `name` varchar(100) NOT NULL,
  `isActive` tinyint(4) NOT NULL DEFAULT 1,
  `config` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`config`)),
  `store_id` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_d311c589b44f1f57b8f22f949b6` (`store_id`),
  CONSTRAINT `FK_d311c589b44f1f57b8f22f949b6` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `stores` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `name` varchar(200) NOT NULL,
  `code` varchar(50) DEFAULT NULL,
  `type` enum('retail','fnb','warehouse','service') NOT NULL DEFAULT 'retail',
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `postal_code` varchar(10) DEFAULT NULL,
  `latitude` decimal(10,8) DEFAULT NULL,
  `longitude` decimal(11,8) DEFAULT NULL,
  `opening_hours` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`opening_hours`)),
  `manager_id` varchar(255) DEFAULT NULL,
  `receipt_header` text DEFAULT NULL,
  `receipt_footer` text DEFAULT NULL,
  `receipt_logo_url` varchar(500) DEFAULT NULL,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_2be771fa4dcfdc26f586264a62e` (`company_id`),
  KEY `FK_0935835219e12e170ad79137da2` (`manager_id`),
  CONSTRAINT `FK_0935835219e12e170ad79137da2` FOREIGN KEY (`manager_id`) REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_2be771fa4dcfdc26f586264a62e` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `subscription_durations` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `plan_id` varchar(255) NOT NULL,
  `duration_months` int(11) NOT NULL,
  `discount_percentage` decimal(5,2) NOT NULL DEFAULT 0.00,
  `final_price` decimal(15,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_e47c7cb78492e0a54366a98cc97` (`plan_id`),
  CONSTRAINT `FK_e47c7cb78492e0a54366a98cc97` FOREIGN KEY (`plan_id`) REFERENCES `subscription_plans` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `subscription_history` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `subscription_id` varchar(255) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `plan_id` varchar(255) DEFAULT NULL,
  `action` enum('created','activated','renewed','upgraded','downgraded','expired','suspended','cancelled','reactivated','trial_started','trial_converted') NOT NULL,
  `old_status` enum('pending','trial','active','past_due','expired','suspended','cancelled') DEFAULT NULL,
  `new_status` enum('pending','trial','active','past_due','expired','suspended','cancelled') DEFAULT NULL,
  `old_end_date` date DEFAULT NULL,
  `new_end_date` date DEFAULT NULL,
  `amount` decimal(10,2) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}' CHECK (json_valid(`metadata`)),
  `performed_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_153e2b7a1a2d9cac822d93fe15f` (`subscription_id`),
  KEY `FK_9c10f9ddcb6b80cf2d159d0da86` (`company_id`),
  KEY `FK_b07e52db045739737b506cac77b` (`plan_id`),
  CONSTRAINT `FK_153e2b7a1a2d9cac822d93fe15f` FOREIGN KEY (`subscription_id`) REFERENCES `subscriptions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_9c10f9ddcb6b80cf2d159d0da86` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_b07e52db045739737b506cac77b` FOREIGN KEY (`plan_id`) REFERENCES `subscription_plans` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `subscription_plans` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `name` varchar(100) NOT NULL,
  `slug` varchar(50) NOT NULL,
  `description` text DEFAULT NULL,
  `price_monthly` decimal(12,2) NOT NULL,
  `price_yearly` decimal(12,2) NOT NULL,
  `setup_fee` decimal(12,2) NOT NULL DEFAULT 0.00,
  `trial_days` int(11) NOT NULL DEFAULT 14,
  `features` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}' CHECK (json_valid(`features`)),
  `max_stores` int(11) NOT NULL DEFAULT 1,
  `max_users` int(11) NOT NULL DEFAULT 5,
  `max_employees` int(11) NOT NULL DEFAULT 10,
  `max_products` int(11) NOT NULL DEFAULT 100,
  `max_transactions_per_month` int(11) NOT NULL DEFAULT 1000,
  `max_customers` int(11) NOT NULL DEFAULT 500,
  `max_storage_mb` int(11) NOT NULL DEFAULT 1000,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `is_popular` tinyint(4) NOT NULL DEFAULT 0,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_0ebf9b0f0cbd7b2fb5b62e3fac` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `subscriptions` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `plan_id` varchar(255) NOT NULL,
  `status` enum('pending','trial','active','past_due','expired','suspended','cancelled') NOT NULL,
  `billing_cycle` enum('monthly','yearly') NOT NULL,
  `current_period_start` timestamp NULL DEFAULT NULL,
  `current_period_end` timestamp NULL DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `grace_period_end_date` date DEFAULT NULL,
  `duration_months` int(11) DEFAULT NULL,
  `trial_start` timestamp NULL DEFAULT NULL,
  `trial_end` timestamp NULL DEFAULT NULL,
  `cancel_at_period_end` tinyint(4) NOT NULL DEFAULT 0,
  `cancelled_at` timestamp NULL DEFAULT NULL,
  `cancellation_reason` text DEFAULT NULL,
  `price` decimal(12,2) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'IDR',
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}' CHECK (json_valid(`metadata`)),
  `pending_renewal` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`pending_renewal`)),
  PRIMARY KEY (`id`),
  KEY `FK_7e3cc01c420db5151aa21360358` (`company_id`),
  KEY `FK_e45fca5d912c3a2fab512ac25dc` (`plan_id`),
  CONSTRAINT `FK_7e3cc01c420db5151aa21360358` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_e45fca5d912c3a2fab512ac25dc` FOREIGN KEY (`plan_id`) REFERENCES `subscription_plans` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `suppliers` (
  `id` varchar(36) NOT NULL,
  `company_id` varchar(255) NOT NULL,
  `supplier_code` varchar(50) NOT NULL,
  `name` varchar(200) NOT NULL,
  `contact_person` varchar(200) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `postal_code` varchar(10) DEFAULT NULL,
  `tax_id` varchar(50) DEFAULT NULL,
  `bank_name` varchar(50) DEFAULT NULL,
  `bank_account_number` varchar(50) DEFAULT NULL,
  `bank_account_name` varchar(200) DEFAULT NULL,
  `payment_terms_days` int(11) NOT NULL DEFAULT 30,
  `notes` text DEFAULT NULL,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_659eca55c043f5b3d858ac2fef` (`supplier_code`),
  KEY `IDX_6a9681499416e80c1ffac4fe86` (`company_id`),
  CONSTRAINT `FK_6a9681499416e80c1ffac4fe86c` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `tables` (
  `id` varchar(36) NOT NULL,
  `table_number` varchar(50) NOT NULL,
  `table_name` varchar(100) DEFAULT NULL,
  `capacity` int(11) NOT NULL,
  `status` enum('available','occupied','reserved','cleaning') NOT NULL DEFAULT 'available',
  `floor` varchar(100) DEFAULT NULL,
  `section` varchar(100) DEFAULT NULL,
  `position_x` int(11) NOT NULL DEFAULT 0,
  `position_y` int(11) NOT NULL DEFAULT 0,
  `company_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `current_transaction_id` varchar(255) DEFAULT NULL,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `REL_6da8004d65dfbaf0c11789480a` (`current_transaction_id`),
  KEY `FK_0fb9f96765782c076466503644e` (`company_id`),
  KEY `FK_1954b33b70ae3e49454cf612f36` (`store_id`),
  CONSTRAINT `FK_0fb9f96765782c076466503644e` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_1954b33b70ae3e49454cf612f36` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_6da8004d65dfbaf0c11789480a2` FOREIGN KEY (`current_transaction_id`) REFERENCES `transactions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `taxes` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `name` varchar(50) NOT NULL,
  `rate` decimal(5,2) NOT NULL,
  `isActive` tinyint(4) NOT NULL DEFAULT 1,
  `isInclusive` tinyint(4) NOT NULL DEFAULT 0,
  `store_id` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_2b5e414bef8c24049d52844a125` (`store_id`),
  CONSTRAINT `FK_2b5e414bef8c24049d52844a125` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `transaction_items` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `productName` varchar(150) NOT NULL,
  `variantName` varchar(100) DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `unitPrice` decimal(12,2) NOT NULL,
  `discountAmount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `subtotal` decimal(12,2) NOT NULL,
  `notes` text DEFAULT NULL,
  `productId` varchar(255) DEFAULT NULL,
  `transaction_id` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_5926425896b30c0d681fe879af0` (`transaction_id`),
  CONSTRAINT `FK_5926425896b30c0d681fe879af0` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `transactions` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `store_id` varchar(255) NOT NULL,
  `shift_id` varchar(255) DEFAULT NULL,
  `employee_id` varchar(255) DEFAULT NULL,
  `customer_id` varchar(255) DEFAULT NULL,
  `transaction_number` varchar(50) NOT NULL,
  `invoice_number` varchar(50) NOT NULL,
  `subtotal` decimal(12,2) NOT NULL,
  `tax_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `discount_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `service_charge` decimal(12,2) NOT NULL DEFAULT 0.00,
  `total` decimal(12,2) NOT NULL,
  `payment_method` enum('cash','qris','edc','bank_transfer','e_wallet') NOT NULL,
  `paid_amount` decimal(12,2) NOT NULL,
  `change_amount` decimal(12,2) NOT NULL DEFAULT 0.00,
  `customer_name` varchar(150) DEFAULT NULL,
  `customer_phone` varchar(20) DEFAULT NULL,
  `status` enum('pending','completed','voided','refunded') NOT NULL DEFAULT 'completed',
  `voided_at` timestamp NULL DEFAULT NULL,
  `voided_by` varchar(255) DEFAULT NULL,
  `void_reason` text DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}' CHECK (json_valid(`metadata`)),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_8cd1b791936b2cdd53d9ec5fdb` (`transaction_number`),
  UNIQUE KEY `IDX_14b6b642161e84ddddc7fb8539` (`invoice_number`),
  KEY `FK_8733562c5e54c31dd1ba8f49915` (`company_id`),
  KEY `FK_ae6c0d854cfbf0ad012cf82be25` (`store_id`),
  KEY `FK_a8d3ae44663921129bda4dcf6df` (`shift_id`),
  KEY `FK_eeaf48e230619e81e05a327b5dc` (`employee_id`),
  KEY `FK_6f09843c214f21a462b54b11e8d` (`customer_id`),
  KEY `FK_0fdb9523e59b53aebc88e3c57a2` (`voided_by`),
  CONSTRAINT `FK_0fdb9523e59b53aebc88e3c57a2` FOREIGN KEY (`voided_by`) REFERENCES `employees` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_6f09843c214f21a462b54b11e8d` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_8733562c5e54c31dd1ba8f49915` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_a8d3ae44663921129bda4dcf6df` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ae6c0d854cfbf0ad012cf82be25` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_eeaf48e230619e81e05a327b5dc` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `usage_tracking` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `metric` enum('stores','users','employees','products','transactions','customers','storage') NOT NULL,
  `count` int(11) NOT NULL DEFAULT 0,
  `period_start` date NOT NULL,
  `period_end` date NOT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '{}' CHECK (json_valid(`metadata`)),
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_fa8e41c60eb713ca1efa6abb4d` (`company_id`,`metric`,`period_start`),
  CONSTRAINT `FK_088f8c034d2922f498fbba09f25` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `users` (
  `id` varchar(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT current_timestamp(6),
  `updated_at` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
  `company_id` varchar(255) NOT NULL,
  `name` varchar(150) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `password_hash` varchar(255) NOT NULL,
  `email_verified` tinyint(4) NOT NULL DEFAULT 0,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `role` enum('owner','admin','manager','accountant') NOT NULL DEFAULT 'admin',
  `permissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '[]' CHECK (json_valid(`permissions`)),
  `avatar_url` varchar(500) DEFAULT NULL,
  `is_active` tinyint(4) NOT NULL DEFAULT 1,
  `last_login_at` timestamp NULL DEFAULT NULL,
  `last_login_ip` varchar(45) DEFAULT NULL,
  `two_factor_enabled` tinyint(4) NOT NULL DEFAULT 0,
  `two_factor_secret` varchar(255) DEFAULT NULL,
  `deleted_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_7ae6334059289559722437bcc1c` (`company_id`),
  CONSTRAINT `FK_7ae6334059289559722437bcc1c` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


SET FOREIGN_KEY_CHECKS = 1;
